# ===============================================================
# 
# Release under GPLv-3.0.
# 
# @file    Makefile
# @brief   
# @author  gnsyxiang <gnsyxiang@163.com>
# @date    31/03 2020 10:48
# @version v0.0.1
# 
# @since    note
# @note     note
# 
#     change log:
#     NO.     Author              Date            Modified
#     00      zhenquan.qiu        31/03 2020      create the file
# 
#     last modified: 31/03 2020 10:48
# ===============================================================




all:
	gcc -fprofile-arcs -ftest-coverage a.c test.c -o test -lgcov


clean:
	rm -rf *.gcda *.gcno test
	rm -rf cover_report
	rm -rf *.info


